# source of inspiration: http://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# No longer C-b, C-a is quicker
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config
bind r source-file ~/.tmux.conf

# split: v->vertical and h->horizontal
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %


# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Mouse is useless, but..
set -g mouse on
